version: '3.8'
services:
   app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: gestion_envoi
    container_name: gestion_envoi
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      
  php-apache-environment:
    container_name: php-apache
    image: php:8.0-apache
    volumes:
      - ./:/var/www
      - ./php/src:/var/www/html/
    ports:
      - 8000:80